export const bookingModel = {
   id_cot:{
      label:'Id',
      field:'id_cot',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   cot_numpas:{
      label:'Pasajeros',
      field:'cot_numpas',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   cot_fecdesde:{
      label:'Fec. desde',
      field:'cot_fecdesde',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cot_fechasta:{
      label:'Fec. hasta',
      field:'cot_fechasta',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   /*id_seg:{
      label:'Seguimiento',
      field:'id_seg',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },*/
   seg:{
      label:'Seguimiento',
      field:'seg',
      fieldRelation:'seg_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   /*id_operador:{
      label:'Id Ope.',
      field:'id_operador',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },*/
   operador:{
      label:'Operador',
      field:'operador',
      fieldRelation:'hot_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },


   
   cot_fec:{
      label:'Fec. Cot',
      field:'cot_fec',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cot_obs:{
      label:'Obs. Cot',
      field:'cot_obs',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cot_correlativo:{
      label:'Cot Correlativo',
      field:'cot_correlativo',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cot_valor:{
      label:'Valor',
      field:'cot_valor',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   /*
   id_usuario:{
      label:'Id Usu.',
      field:'id_usuario',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   */
   usuario:{
      label:'Usuario Crea',
      field:'usuario',
      fieldRelation:'usu_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usuconf:{
      label:'Usuario Confirma',
      field:'usuconf',
      fieldRelation:'usu_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usuanula:{
      label:'Usuario Anula',
      field:'usuanula',
      fieldRelation:'usu_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   mon:{
      label:'Moneda',
      field:'mon',
      fieldRelation:'mon_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   area:{
      label:'Area',
      field:'area',
      fieldRelation:'area_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cot_pripas:{
      label:'Nom. Pasajero',
      field:'cot_pripas',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cot_pripas2:{
      label:'Ape. Pasajero',
      field:'cot_pripas2',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cot_numfile:{
      label:'N° File',
      field:'cot_numfile',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
}

// export default bookingModel