export const bookModel = {
   libro_id:{
      label:'Libro ID',
      field:'libro_id',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   libro_nombre:{
      label:'Libro Código',
      field:'libro_codigo',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   libro_nombre:{
      label:'Libro Nombre',
      field:'libro_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   libro_descripcion:{
      label:'Libro Descripcion',
      field:'libro_descripcion',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
}