export const bookModel = {
   book_id:{
      label:'Id',
      field:'book_id',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   field_1:{
      label:'Campo 1',
      field:'field_1',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   field_2:{
      label:'Campo 2',
      field:'field_2',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   field_3:{
      label:'Campo 3',
      field:'field_3',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   field_4:{
      label:'Campo 4',
      field:'field_4',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   field_5:{
      label:'Campo 5',
      field:'field_5',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },   
   field_6:{
      label:'Campo 6',
      field:'field_6',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
}