export const Establecimiento = {
  field1:{
    label:'ID',
    field:'establecimiento_id',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field2:{
    label:'Nombre',
    field:'establecimiento_nombre',
    defaultValue:'Sin código',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field3:{
    label:'Dirección',
    field:'establecimiento_direccion',
    defaultValue:'Sin dirección',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field4:{
    label:'Descripción',
    field:'establecimiento_descripcion',
    defaultValue:'Sin descripción',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field5:{
    label:'Región',
    field:'region', //la relacion en el modelo del backend en laravel
    fieldRelation:'region_nombre',
    defaultValue:'Sin región',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field6:{
    label:'Comuna',
    field:'comuna', //la relacion en el modelo del backend en laravel
    fieldRelation:'comuna_nombre',
    defaultValue:'Sin comuna',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
}