export const FichaTrabajador = {
  field1:{
    label:'ID',
    field:'ficha_trabajador_id',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field2:{
    label:'Rut',
    field:'ficha_rut',
    defaultValue:'Sin rut',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field3:{
    label:'Dígito Verificador',
    field:'ficha_dv',
    defaultValue:'Sin dígito',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field4:{
    label:'Género',
    field:'ficha_genero',
    defaultValue:'Sin genero',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },


  field5:{
    label:'Nombre',
    field:'ficha_nombre',
    defaultValue:'Sin nombre',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },

  field6:{
    label:'Apellido Paterno',
    field:'ficha_apellido_paterno',
    defaultValue:'Sin apellido paterno',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field7:{
    label:'Apellido Materno',
    field:'ficha_apellido_materno',
    defaultValue:'Sin apellido materno',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field8:{
    label:'Fecha Nacimiento',
    field:'ficha_fecha_nacimiento',
    defaultValue:'Sin fecha nacimiento',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field9:{
    label:'Fecha Ingreso',
    field:'ficha_fecha_ingreso',
    defaultValue:'Sin fecha ingreso',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },

  field10:{
    label:'Cargo',
    field:'cargo', //la relacion en el modelo del backend en laravel
    fieldRelation:'cargo_nombre',
    defaultValue:'Sin cargo',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field11:{
    label:'Rbd',
    field:'rbd', //la relacion en el modelo del backend en laravel
    fieldRelation:'rbd_nombre',
    defaultValue:'Sin rbd',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
}