export const FichaTrabajador = {
  field1:{
    label:'ID',
    field:'ficha_trabajador_id',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field2:{
    label:'Rut',
    field:'ficha_rut',
    defaultValue:'Sin rut',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field3:{
    label:'Dirección',
    field:'ficha_dv',
    defaultValue:'Sin dígito',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field4:{
    label:'Descripción',
    field:'ficha_genero',
    defaultValue:'Sin genero',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },


  field5:{
    label:'Nombre',
    field:'ficha_nombre',
    defaultValue:'Sin nombre',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },

  field6:{
    label:'Apellido Paterno',
    field:'ficha_apellido_paterno',
    defaultValue:'Sin apellido paterno',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field7:{
    label:'Apellido Materno',
    field:'ficha_apellido_materno',
    defaultValue:'Sin apellido materno',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field8:{
    label:'Fecha Nacimiento',
    field:'ficha_fecha_nacimiento',
    defaultValue:'Sin fecha nacimiento',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field9:{
    label:'Fecha Ingreso',
    field:'ficha_fecha_ingreso',
    defaultValue:'Sin fecha ingreso',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field10:{
    label:'Sueldo Base',
    field:'ficha_sueldo_base',
    defaultValue:'Sin sueldo base',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field11:{
    label:'Horas Semanales',
    field:'ficha_horas_semanales',
    defaultValue:'Sin horas semanales',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field12:{
    label:'Horas Extras',
    field:'ficha_horas_extras',
    defaultValue:'Sin horas extras',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field13:{
    label:'Bono',
    field:'ficha_bono',
    defaultValue:'Sin bono',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },




  field14:{
    label:'Establecimiento',
    field:'establecimiento', //la relacion en el modelo del backend en laravel
    fieldRelation:'establecimiento',
    defaultValue:'Sin establecimiento',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field15:{
    label:'Subvención',
    field:'subvencion', //la relacion en el modelo del backend en laravel
    fieldRelation:'subvencion',
    defaultValue:'Sin subvención',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field16:{
    label:'Cargo',
    field:'cargo', //la relacion en el modelo del backend en laravel
    fieldRelation:'cargo',
    defaultValue:'Sin cargo',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field17:{
    label:'Rbd',
    field:'rbd', //la relacion en el modelo del backend en laravel
    fieldRelation:'rbd',
    defaultValue:'Sin rbd',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
}