export const hotelModel = {
   id_hotel:{
      label:'Id',
      field:'id_hotel',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   hot_nombre:{
      label:'Nombre',
      field:'hot_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hot_direccion:{
      label:'Dirección',
      field:'hot_direccion',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   comuna:{
      label:'Comuna',
      field:'comuna',
      fieldRelation:'com_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   ciudad:{
      label:'Ciudad',
      field:'ciudad',
      fieldRelation:'ciu_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   cat:{
      label:'Categoría',
      field:'cat',
      fieldRelation:'cat_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hot_estado:{
      label:'Estado',
      field:'hot_estado',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hot_fono:{
      label:'Fono',
      field:'hot_fono',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hot_email:{
      label:'E-mail',
      field:'hot_email',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
}

//export default hotelModel

/*
etiqueta:'Id',
campo:'id_hotel',
campoRelacion:'',
visible:false,
filtroActivo: false,
textoBusquedaEnCampo:'',
textosEnBusqueda:[],
filtroRestrictivo:false,
*/