export const Libro = {
  field1:{
    label:'ID',
    field:'libro_id',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field2:{
    label:'Código',
    field:'libro_codigo',
    defaultValue:'Sin código',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field3:{
    label:'Nombre',
    field:'libro_nombre',
    defaultValue:'Sin nombre',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field4:{
    label:'Descripción',
    field:'libro_descripcion',
    defaultValue:'Sin descripción',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
}