export const rateModel = {
   id_hotdet:{
      label:'Id',
      field:'id_hotdet',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   /*
   id_hotel:{
      label:'Id hotel',
      field:'id_hotel',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   */
   hd_fecdesde:{
      label:'Fec. desde',
      field:'hd_fecdesde',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hd_fechasta:{
      label:'Fec. Hasta',
      field:'hd_fechasta',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hd_sgl:{
      label:'$ SGL',
      field:'hd_sgl',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hd_dbl:{
      label:'$ DBL',
      field:'hd_dbl',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hd_tpl:{
      label:'$ TPL',
      field:'hd_tpl',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hd_markup:{
      label:'Markup',
      field:'hd_markup',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   /*
   hd_estado:{
      label:'Estado',
      field:'hd_estado',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   */
   tipotarifa:{
      label:'Tipo Tarifa',
      field:'tipotarifa',
      fieldRelation:'tt_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   tipohabitacion:{
      label:'Tipo Habitacion',
      field:'tipohabitacion',
      fieldRelation:'th_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   area:{
      label:'Area',
      field:'area',
      fieldRelation:'area_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   hotel:{
      label:'Hotel',
      field:'hotel',
      fieldRelation:'hot_nombre',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   mon:{
      label:'Tipo Moneda',
      field:'mon',
      fieldRelation:'mon_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
}

//export default rateModel