export const Rbd = {
  field1:{
    label:'ID',
    field:'rbd_id',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field2:{
    label:'Código',
    field:'rbd_codigo',
    defaultValue:'Sin código',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:false,
    isFilterActive: false,
    isRestrictiveFilter:false,
  },
  field3:{
    label:'Nombre',
    field:'rbd_nombre',
    defaultValue:'Sin nombre',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field4:{
    label:'Descripción',
    field:'rbd_descripcion',
    defaultValue:'Sin descripción',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
  field5:{
    label:'Establecimiento',
    field:'establecimiento', //la relacion en el modelo del backend en laravel
    fieldRelation:'establecimiento_nombre',
    defaultValue:'Sin establecimiento',
    searchTextInField:'',
    arrayTextsInSearch:[],
    isVisible:true,
    isFilterActive: false,    
    isRestrictiveFilter:false,
  },
}