export const userModel = {
   id_usuario:{
      label:'Id',
      field:'id_usuario',
      searchTextInField:'',
      arrayTextsInSearch:[],
      isVisible:false,
      isFilterActive: false,
      isRestrictiveFilter:false,
   },
   usu_rut:{
      label:'Rut',
      field:'usu_rut',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usu_login:{
      label:'Usuario',
      field:'usu_login',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usu_password:{
      label:'Password',
      field:'usu_password',
      isVisible:true,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usu_nombre:{
      label:'Nombre',
      field:'usu_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usu_pat:{
      label:'Ap. Paterno',
      field:'usu_pat',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usu_mat:{
      label:'Ap. Materno',
      field:'usu_mat',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usu_mail:{
      label:'E-mail',
      field:'usu_mail',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
   usu_enviar_correo:{
      label:'E-mail',
      field:'usu_mail',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },


   empresa:{
      label:'Empresa',
      field:'empresa',
      fieldRelation:'hot_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },

   tipo:{
      label:'Tipo Usuario',
      field:'tipo',
      fieldRelation:'tu_usuario',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },

   hotel:{
      label:'Hotel',
      field:'hotel',
      fieldRelation:'hot_nombre',
      isVisible:false,
      isFilterActive: false,
      searchTextInField:'',
      arrayTextsInSearch:[],
      isRestrictiveFilter:false,
   },
}

//export default userModel